# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [2]:
#### Start solution ####
vector1 <- c("a","h","m","a","d")
print(vector1)
name = paste(vector1,collapse = "")
print(name)

[1] "a" "h" "m" "a" "d"
[1] "ahmad"


In [3]:
var1 <- 100:120
print(var1)

 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120


In [4]:
numbers <- seq(from = 2, to = 18, by = 2)
mat1 = matrix(numbers,nrow = 3,ncol=3)
print(mat1)

     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18


In [5]:
row.names(mat1) <- c("r1","r2","r3")
colnames(mat1) <- c("c1","c2","c3")
print(mat1)

   c1 c2 c3
r1  2  8 14
r2  4 10 16
r3  6 12 18


In [6]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [7]:
#### Start solution ####

In [8]:
emp_status <- factor(c("Employed","Employed","Unemployed","Self-Employed","Unemployed","Employed","Unemployed","Self-Employed","Self-Employed"),levels = c("Employed","Unemployed","Self-Employed"))
print(emp_status)

[1] Employed      Employed      Unemployed    Self-Employed Unemployed   
[6] Employed      Unemployed    Self-Employed Self-Employed
Levels: Employed Unemployed Self-Employed


In [9]:
table(emp_status)

emp_status
     Employed    Unemployed Self-Employed 
            3             3             3 

In [10]:
unclass(emp_status)

[1] 1 1 2 3 2 1 2 3 3
attr(,"levels")
[1] "Employed"      "Unemployed"    "Self-Employed"

In [11]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [12]:
#### Start solution ####

In [13]:
bank_customers <- data.frame(CustomerID=101:105,hasAccount=c(FALSE,TRUE,TRUE,TRUE,NA),totalBalance= c(NA,10000,0,2000,NA))

row.names(bank_customers)<-c("Alicia","Nancy","Fernando","Louis","Diane")
print(bank_customers)
#new record added
#newEmployee <- data.frame(CustomerID=106,hasAccount=TRUE,totalBalance=500)
#rbind(bank_customers,newEmployee)

         CustomerID hasAccount totalBalance
Alicia          101      FALSE           NA
Nancy           102       TRUE        10000
Fernando        103       TRUE            0
Louis           104       TRUE         2000
Diane           105         NA           NA


In [14]:
nrow(bank_customers)

[1] 5

In [15]:
dimnames(bank_customers)

[[1]]
[1] "Alicia"   "Nancy"    "Fernando" "Louis"    "Diane"   

[[2]]
[1] "CustomerID"   "hasAccount"   "totalBalance"

In [16]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [17]:
#### Start solution ####

In [18]:
# Question 1(a)
getPrimeNumbers <- function(var2){
     
   primeMarker= TRUE  
   var3 <- c()
   for (x in var2){
     if(x == 1){
          var3 <- c(var3,x)
          next
     }
     for (y in var2){
          if(y == 1)next
          else if(x == y)next
          
          if ( x %% y == 0){
               primeMarker = FALSE
               break}
          else {
               primeMarker= TRUE
               
          }
          
     } 
     
     if(primeMarker == TRUE){
          # vector concatenation
          var3 <- c(var3,x)
          primeMarker == FALSE
     }
   }
   var3
}
var2 <- 1:100
result = getPrimeNumbers(var2)
cat("Prime Numbers are: ",result)

Prime Numbers are:  1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

In [19]:
# Question 1 (b)
getithPrimeNumber <- function(var,check){
     while(TRUE){
          primeNumbers = getPrimeNumbers(seq(1:var))
          length = length(primeNumbers)
          if(length == check){
               break
          }
          var = var + 1
     
     }
     # return 
     primeNumbers[length]
}

# Use Custom Function
var = 1
check = 10
result = getithPrimeNumber(var,check)
cat(check,"th Prime Number is:",result,sep = "")

10th Prime Number is:23

In [20]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [21]:
#### Start solution ####

In [22]:
# Create Matrix 3x3
mat_1 = matrix(1:9,3,3)

In [23]:
# print matrix by elements
for (i in seq_len(nrow(mat_1))){
     for(j in seq_len(ncol(mat_1))){
          cat("Element at Position (",i,",",j,") is :",mat_1[i,j],"\n")
     }
}

Element at Position ( 1 , 1 ) is : 1 
Element at Position ( 1 , 2 ) is : 4 
Element at Position ( 1 , 3 ) is : 7 
Element at Position ( 2 , 1 ) is : 2 
Element at Position ( 2 , 2 ) is : 5 
Element at Position ( 2 , 3 ) is : 8 
Element at Position ( 3 , 1 ) is : 3 
Element at Position ( 3 , 2 ) is : 6 
Element at Position ( 3 , 3 ) is : 9 


In [24]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [25]:
#### Start solution ####

In [26]:
gcd <- function(a,b){
     if(a<b) smaller = a    
     else smaller = b

     for (i in 1:smaller) {
          if((a %% i == 0) && (b %% i == 0)){
               hcf = i
          }
     }
     
     cat("Greatest Common Divisor:",hcf)
     return(hcf)
}
num1 = 72
num2 = 120

In [27]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [28]:
#### Start solution ####

In [29]:
allConditionsMeet <- function(a,b){

     if((a == TRUE)&&(b==TRUE)){
          return(TRUE)
     }
}
exp1 = 2 < 5
exp2 = 5 >= 0
result = allConditionsMeet(exp1,exp2)
cat("Result is:",result,"\n")

print("Arguments:")
print(formals(allConditionsMeet))

Result is: TRUE 
[1] "Arguments:"
$a


$b




In [30]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [31]:
#### Start solution ####

In [32]:
#Create Matrices
matrix_1 <- matrix(1:6,2,3)
matrix_2 <- matrix(1:6,3,2)
matrix_1
matrix_2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [33]:
# element-wise multiplication
#elements = c()
#for (i in seq_len(nrow(matrix_1))){
#     a = c(matrix_1[i,]) * c(matrix_2[i,])
#     elements <- c(elements,a)
#}
#elementWiseMultiplication = matrix(elements,2,3)
#elementWiseMultiplication

# approach 2:
element_mat = c(matrix_1) * c(matrix_2)
print(matrix(element_mat,2,3))
# approach 3:
#print("Element Wise Multiplication: ",matrix_1 * matrix_2)

     [,1] [,2] [,3]
[1,]    1    9   25
[2,]    4   16   36


In [34]:
# matrix multiplication
matrixMultiplication = matrix_1 %*% matrix_2
matrixMultiplication

[,1] [,2]
[1,] 22   49  
[2,] 28   64

In [35]:
# determinant of matrix
matrix_3 = matrix(5:8,2,2)
matrix_3
print(det(matrix_3))

[,1] [,2]
[1,] 5    7   
[2,] 6    8

[1] -2


In [36]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [37]:
#### Start solution ####

In [38]:
# get date & time
curr_time = Sys.time()
curr_time

curr_date = as.Date(curr_time)
curr_date 

[1] "2022-09-07 07:14:27 PDT"

[1] "2022-09-07"

In [39]:
# get Objects
datetObject = as.POSIXct(curr_date)
datetObject

timeObject = as.POSIXlt(curr_time)
names(unclass(timeObject))

[1] "2022-09-06 17:00:00 PDT"

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [40]:
#get attributes
print(timeObject$wday)
print(timeObject$year)
print(timeObject$sec)
print(timeObject$hour)

[1] 3
[1] 122
[1] 27.76298
[1] 7


In [41]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [42]:
#### Start solution ####

In [43]:
dateWithTimeZOne = as.POSIXlt(Sys.time(),tz="GMT-5")
# Print time for both time zones
timeObject
dateWithTimeZOne

# difference
difference = timeObject - dateWithTimeZOne
difference

Warning message in as.POSIXlt.POSIXct(Sys.time(), tz = "GMT-5"):
"unknown timezone 'GMT-5'"


[1] "2022-09-07 07:14:27 PDT"

[1] "2022-09-07 19:14:28 GMT"

Warning message in as.POSIXct.POSIXlt(time2):
"unknown timezone 'GMT-5'"


Time difference of -0.306133 secs

In [44]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [45]:
#### Start solution ####

In [46]:
calculateMSD <- function(data) c(mean=mean(data),standard_deviation =sd(data))
# data
numbers = 100:150

# lapply returned list
lapply(list(numbers),calculateMSD)

[[1]]
              mean standard_deviation 
         125.00000           14.86607

In [47]:
#sapply returned data (matrix,array)
sapply(list(numbers),calculateMSD)

[,1]     
mean               125.00000
standard_deviation  14.86607

In [48]:
# apply work on array or matrix, returned (matrix,array)
apply(matrix(numbers,1,51),MARGIN =  1,FUN = calculateMSD)

[,1]     
mean               125.00000
standard_deviation  14.86607

In [49]:
# tapply works on ragged array -- vector returned array
# create a factor of same length as of data : for indexing
f = gl(5,5)
tapply(numbers[26:50], f, calculateMSD)
# printed mean with indexing of 5 and standard deviation with levels 5

$`1`
              mean standard_deviation 
        127.000000           1.581139 

$`2`
              mean standard_deviation 
        132.000000           1.581139 

$`3`
              mean standard_deviation 
        137.000000           1.581139 

$`4`
              mean standard_deviation 
        142.000000           1.581139 

$`5`
              mean standard_deviation 
        147.000000           1.581139

In [50]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [51]:
#### Start solution ####

In [52]:
matrix_4 <- matrix(21:36,4,4)
matrix_4

[,1] [,2] [,3] [,4]
[1,] 21   25   29   33  
[2,] 22   26   30   34  
[3,] 23   27   31   35  
[4,] 24   28   32   36

In [53]:
rm = rowMeans(matrix_4)
cat("Row Means:",rm)

Row Means: 27 28 29 30

In [54]:
cm = colMeans(matrix_4)
cat("Column Means:",cm)

Column Means: 22.5 26.5 30.5 34.5

In [55]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [56]:
library(datasets)

In [57]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [58]:
#### Start solution ####

In [59]:
split_data = split(Orange,Orange$circumference)
#class(split_data)
#names(unclass(split_data))

# Data for 30
split_data$`30`

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

In [60]:
# Data for 75
split_data$`75`

Tree age circumference
17 3    664 75

In [61]:
#average age for 30
data1 <- split_data$`30`
dataWithAge1 = list(data1$age)

age1Mean =sapply(dataWithAge1, mean)
cat("Average age for 30:",age1Mean)

Average age for 30: 118

In [62]:
# average age for 214
data2 <- split_data$`214`
dataWithAge2 = list(data2$age)

age2Mean =sapply(dataWithAge2, mean)
cat("Average age for 214:",age2Mean)

Average age for 214: 1582

In [63]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!